CREATE TABLE IF NOT EXISTS crypto_ticker (
    id SERIAL PRIMARY KEY,
    symbol VARCHAR(50),
    priceChange NUMERIC,
    priceChangePercent NUMERIC,
    weightedAvgPrice NUMERIC,
    prevClosePrice NUMERIC,
    lastPrice NUMERIC,
    lastQty NUMERIC,
    bidPrice NUMERIC,
    bidQty NUMERIC,
    askPrice NUMERIC,
    askQty NUMERIC,
    openPrice NUMERIC,
    highPrice NUMERIC,
    lowPrice NUMERIC,
    volume NUMERIC,
    quoteVolume NUMERIC,
    openTime BIGINT,
    closeTime BIGINT,
    firstId BIGINT,
    lastId BIGINT,
    count INT,
    processed BOOLEAN DEFAULT FALSE
);
