CREATE TABLE IF NOT EXISTS btcusdt_data (
    id SERIAL PRIMARY KEY,
    price VARCHAR(50),
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    processed BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS solusdt_data (
    id SERIAL PRIMARY KEY,
    price VARCHAR(50),
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    processed BOOLEAN DEFAULT FALSE
);